dashboards:
  CF_ACCESS_ATHENA ANALYSIS:
    name: cf_access_athena analysis
    templateId: cf_access_athena-analysis
    sourceAccountId: '304308874769'
    region: us-east-1
    dashboardId: cf_access_athena-analysis
    dependsOn:
      datasets:
      - cf_access_athena
datasets:
  cf_access_athena:
    Data:
      DataSetId: b88a32d7-b767-41bd-939a-9546a7c9cef0
      Name: cf_access_athena
      PhysicalTableMap:
        6f014f78-8672-40ec-9ca9-78ccd023c9fb:
          RelationalTable:
            DataSourceArn: ${athena_datasource_arn}
            Catalog: AwsDataCatalog
            Schema: ${athena_database_name}
            Name: cf_access_athena
            InputColumns:
            - Name: date
              Type: DATETIME
            - Name: time
              Type: STRING
            - Name: location
              Type: STRING
            - Name: bytes
              Type: INTEGER
            - Name: request_ip
              Type: STRING
            - Name: method
              Type: STRING
            - Name: host
              Type: STRING
            - Name: uri
              Type: STRING
            - Name: status
              Type: INTEGER
            - Name: referrer
              Type: STRING
            - Name: user_agent
              Type: STRING
            - Name: query_string
              Type: STRING
            - Name: cookie
              Type: STRING
            - Name: result_type
              Type: STRING
            - Name: request_id
              Type: STRING
            - Name: host_header
              Type: STRING
            - Name: request_protocol
              Type: STRING
            - Name: request_bytes
              Type: INTEGER
            - Name: time_taken
              Type: DECIMAL
            - Name: xforwarded_for
              Type: STRING
            - Name: ssl_protocol
              Type: STRING
            - Name: ssl_cipher
              Type: STRING
            - Name: response_result_type
              Type: STRING
            - Name: http_version
              Type: STRING
            - Name: fle_status
              Type: STRING
            - Name: fle_encrypted_fields
              Type: INTEGER
            - Name: c_port
              Type: INTEGER
            - Name: time_to_first_byte
              Type: DECIMAL
            - Name: x_edge_detailed_result_type
              Type: STRING
            - Name: sc_content_type
              Type: STRING
            - Name: sc_content_len
              Type: INTEGER
            - Name: sc_range_start
              Type: INTEGER
            - Name: sc_range_end
              Type: INTEGER
      LogicalTableMap:
        065049f2-4d12-4e55-ab8d-ec3b6bc777d2:
          Alias: cf_access_athena
          DataTransforms:
          - CreateColumnsOperation:
              Columns:
              - ColumnName: Device
                ColumnId: 9d4acff3-6dc2-44e5-9bff-1011b3fcc5df
                Expression: ifelse((contains({user_agent},"android",CASE_INSENSITIVE)
                  OR contains({user_agent},"iphone", CASE_INSENSITIVE) OR contains({user_agent},"ipad",
                  CASE_INSENSITIVE)),'Mobile', 'Desktop')
          - ProjectOperation:
              ProjectedColumns:
              - date
              - time
              - location
              - bytes
              - request_ip
              - method
              - host
              - uri
              - status
              - referrer
              - user_agent
              - query_string
              - cookie
              - result_type
              - request_id
              - host_header
              - request_protocol
              - request_bytes
              - time_taken
              - xforwarded_for
              - ssl_protocol
              - ssl_cipher
              - response_result_type
              - http_version
              - fle_status
              - fle_encrypted_fields
              - c_port
              - time_to_first_byte
              - x_edge_detailed_result_type
              - sc_content_type
              - sc_content_len
              - sc_range_start
              - sc_range_end
              - Device
          Source:
            PhysicalTableId: 6f014f78-8672-40ec-9ca9-78ccd023c9fb
      ImportMode: SPICE
views: {}
